// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjaManager.Data;

#nullable disable

namespace NinjaManager.Data.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20240926123149_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EquipmentNinja", b =>
                {
                    b.Property<int>("EquipmentsId")
                        .HasColumnType("int");

                    b.Property<int>("NinjasId")
                        .HasColumnType("int");

                    b.HasKey("EquipmentsId", "NinjasId");

                    b.HasIndex("NinjasId");

                    b.ToTable("EquipmentNinja");
                });

            modelBuilder.Entity("NinjaManager.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Head"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Necklace"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chest"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hands"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ring"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Feet"
                        });
                });

            modelBuilder.Entity("NinjaManager.Data.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agility = 0,
                            CategoryId = 1,
                            Intelligence = 0,
                            Name = "Leather Helmet",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 2,
                            Agility = 0,
                            CategoryId = 1,
                            Intelligence = 0,
                            Name = "Iron Helmet",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 3,
                            Agility = 0,
                            CategoryId = 1,
                            Intelligence = 0,
                            Name = "Golden Helmet",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 4,
                            Agility = 0,
                            CategoryId = 1,
                            Intelligence = 0,
                            Name = "Diamond Helmet",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 5,
                            Agility = 0,
                            CategoryId = 1,
                            Intelligence = 0,
                            Name = "Mythic Helmet",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 6,
                            Agility = 0,
                            CategoryId = 2,
                            Intelligence = 0,
                            Name = "Leather Necklace",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 7,
                            Agility = 0,
                            CategoryId = 2,
                            Intelligence = 0,
                            Name = "Iron Necklace",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 8,
                            Agility = 0,
                            CategoryId = 2,
                            Intelligence = 0,
                            Name = "Golden Necklace",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 9,
                            Agility = 0,
                            CategoryId = 2,
                            Intelligence = 0,
                            Name = "Diamond Necklace",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 10,
                            Agility = 0,
                            CategoryId = 2,
                            Intelligence = 0,
                            Name = "Mythic Necklace",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 11,
                            Agility = 0,
                            CategoryId = 3,
                            Intelligence = 0,
                            Name = "Leather Chestplate",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 12,
                            Agility = 0,
                            CategoryId = 3,
                            Intelligence = 0,
                            Name = "Iron Chestplate",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 13,
                            Agility = 0,
                            CategoryId = 3,
                            Intelligence = 0,
                            Name = "Golden Chestplate",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 14,
                            Agility = 0,
                            CategoryId = 3,
                            Intelligence = 0,
                            Name = "Diamond Chestplate",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 15,
                            Agility = 0,
                            CategoryId = 3,
                            Intelligence = 0,
                            Name = "Mythic Chestplate",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 16,
                            Agility = 0,
                            CategoryId = 4,
                            Intelligence = 0,
                            Name = "Leather Gloves",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 17,
                            Agility = 0,
                            CategoryId = 4,
                            Intelligence = 0,
                            Name = "Iron Gloves",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 18,
                            Agility = 0,
                            CategoryId = 4,
                            Intelligence = 0,
                            Name = "Golden Gloves",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 19,
                            Agility = 0,
                            CategoryId = 4,
                            Intelligence = 0,
                            Name = "Diamond Gloves",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 20,
                            Agility = 0,
                            CategoryId = 4,
                            Intelligence = 0,
                            Name = "Mythic Gloves",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 21,
                            Agility = 0,
                            CategoryId = 5,
                            Intelligence = 0,
                            Name = "Leather Ring",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 22,
                            Agility = 0,
                            CategoryId = 5,
                            Intelligence = 0,
                            Name = "Iron Ring",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 23,
                            Agility = 0,
                            CategoryId = 5,
                            Intelligence = 0,
                            Name = "Golden Ring",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 24,
                            Agility = 0,
                            CategoryId = 5,
                            Intelligence = 0,
                            Name = "Diamond Ring",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 25,
                            Agility = 0,
                            CategoryId = 5,
                            Intelligence = 0,
                            Name = "Mythic Ring",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 26,
                            Agility = 0,
                            CategoryId = 6,
                            Intelligence = 0,
                            Name = "Leather Boots",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 27,
                            Agility = 0,
                            CategoryId = 6,
                            Intelligence = 0,
                            Name = "Iron Boots",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 28,
                            Agility = 0,
                            CategoryId = 6,
                            Intelligence = 0,
                            Name = "Golden Boots",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 29,
                            Agility = 0,
                            CategoryId = 6,
                            Intelligence = 0,
                            Name = "Diamond Boots",
                            Price = 300,
                            Strength = 0
                        },
                        new
                        {
                            Id = 30,
                            Agility = 0,
                            CategoryId = 6,
                            Intelligence = 0,
                            Name = "Mythic Boots",
                            Price = 300,
                            Strength = 0
                        });
                });

            modelBuilder.Entity("NinjaManager.Data.Ninja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ninjas");
                });

            modelBuilder.Entity("EquipmentNinja", b =>
                {
                    b.HasOne("NinjaManager.Data.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaManager.Data.Ninja", null)
                        .WithMany()
                        .HasForeignKey("NinjasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NinjaManager.Data.Equipment", b =>
                {
                    b.HasOne("NinjaManager.Data.Category", "Category")
                        .WithMany("Equipments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NinjaManager.Data.Category", b =>
                {
                    b.Navigation("Equipments");
                });
#pragma warning restore 612, 618
        }
    }
}
